# Generated by Django 5.0.3 on 2025-02-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faucet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failed", "Failed")], max_length=10
            ),
        ),
    ]
